name: Build

on:
  workflow_dispatch:
    inputs:
      pypi_token:
        description: API token for PyPI uploads
        required: true
      pypi_repo_url:
        description: PyPI repo url (default https://upload.pypi.org/legacy/)
        required: true
        type: choice
        options:
        - https://upload.pypi.org/legacy/
        - https://test.pypi.org/legacy/
        # default: https://upload.pypi.org/legacy/

jobs:
  build_python_dists:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone source
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build Python dists
      run: |
        set -e
        python -V
        python -m pip install build

        rm -rf dist/
        
        python -m build .

        dist_tarballs=(dist/*.tar.gz)
        dist_wheels=(dist/*.whl)
        if (( ${#dist_tarballs[@]} != 1 || ${#dist_wheels[@]} != 1 )); then
          echo 'unexpected output in dist/ - expected one tarball and one wheel'
          ls -l dist/
          exit 1
        fi

    - name: Upload to PyPI
      run: |
        set -e        
        python -m pip install twine
        
        twine upload dist/*.tar.gz dist/*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ github.events.inputs.pypi_token }}
        TWINE_REPOSITORY_URL: ${{ github.events.inputs.pypi_repo_url }}
        TWINE_NON_INTERACTIVE: '1'
