name: Runner Container Builds
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+**'
  workflow_dispatch:
jobs:
  containers:
    strategy:
      matrix:
        arch: [x86_64]
    runs-on: ubuntu-22.04
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: setup containmint for multi-arch builds via core-ci workers
      run: |
        python -m pip install https://github.com/ansible/containmint/archive/refs/tags/v0.1.0.tar.gz
    - name: build/push container on remote
      run: |
        containmint build --tag quay.io/rolpdog/ansible-runner:devel --context .
  
